apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: flask-request
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
        wait_time = between(1, 3)

        @task
        def my_task(self):
            # Simulate normal requests to the root endpoint
            self.client.get("/")

        @task
        def health_check(self):
            # Simulate a health check request to the /health endpoint
            self.client.get("/health")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: flask-request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        args: ["-f", "/locust/locustfile.py", "--host", "http://flask-request"]
        ports:
        - containerPort: 8089
        volumeMounts:
        - name: locust-scripts
          mountPath: /locust
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: flask-request
spec:
  selector:
    app: locust
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
