apiVersion: v1
kind: Service
metadata:
  name: flask-request
  namespace: flask-request
spec:
  selector:
    app: flask-request
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
